---
deployment:
  tasks:
    - export DEPLOYPATH=/home/birthday/public_html
    - /bin/cp -R * $DEPLOYPATH/
    - /bin/cp .htaccess $DEPLOYPATH/
    - /bin/cp package.json $DEPLOYPATH/
    - /bin/cp next.config.js $DEPLOYPATH/
