---
deployment:
  tasks:
    - export DEPLOYPATH=/home/birthday/public_html
    # First, clear the deployment directory
    - /bin/rm -rf $DEPLOYPATH/*
    # Copy the built files
    - /bin/cp -R out/* $DEPLOYPATH/
    - /bin/cp -R public/* $DEPLOYPATH/public/
    # Copy necessary configuration files
    - /bin/cp .htaccess $DEPLOYPATH/
    - /bin/cp package.json $DEPLOYPATH/
    - /bin/cp next.config.js $DEPLOYPATH/
    # Set proper permissions
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;
