---
deployment:
  tasks:
    - export DEPLOYPATH=/home/birthday/public_html
    # First, clear the deployment directory
    - /bin/rm -rf $DEPLOYPATH/*
    # Copy all built files from out directory
    - /bin/cp -R out/. $DEPLOYPATH/
    # Copy public assets
    - /bin/cp -R public/. $DEPLOYPATH/
    # Set proper permissions
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec /bin/chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec /bin/chmod 644 {} \;
