---
deployment:
  tasks:
    - export DEPLOYPATH=/home/username/public_html/
    - /bin/cp -R public/* $DEPLOYPATH
    - /bin/cp -R .next/* $DEPLOYPATH/_next
    - /bin/cp -R out/* $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp package.json $DEPLOYPATH
    - /bin/cp next.config.js $DEPLOYPATH
